- src/components/UserMenu.jsx
- src/containers/AuthContainer.jsx
- src/styles/components/user-menu.styl
In the header for logged in users. The styling with this one was a bit hairy with grommet because grommet is very opinionated about the styling of dropdown menus. So that's a -1 in this use case, but I got it looking pretty close to the design.
> A working and styled user menu

- src/components/common/ClassroomCreateForm.spec.jsx
- src/components/common/ClassroomManager.jsx
- src/components/common/ClassroomManager.spec.jsx
- src/containers/common/ClassroomCreateFormContainer.jsx
- src/containers/common/ClassroomCreateFormContainer.spec.jsx
- src/containers/common/ClassroomManagerContainer.jsx
- src/containers/common/ClassroomManagerContainer.spec.jsx
- src/ducks/classrooms.js
I wrote a bunch of unit tests for some of the newer components that I wrote. I fixed some issues that I found along the way. I probably should be better about TDD :-)
> Classroom unit tests

- src/components/common/ClassroomEditor.jsx
- src/components/common/ClassroomManager.jsx
- src/containers/common/ClassroomManagerContainer.jsx
- src/ducks/classrooms.js
- src/styles/components/classroom-editor.styl
- src/styles/components/classroom-manager.styl
* This PR follows the following comments: https://github.com/zooniverse/edu-api-front-end/issues/6#issuecomment-323368841
* The idea is to add a new view to the Classrooms Management system (specifically tailored for I2A at the moment, but generalisable in the future) which allows a Teacher to:
* View the details of a single classroom (description, school, etc)
* OPTIONALLY: Edit the details of a single classroom. (Or if not, place the necessary hooks for a future PR.)
* View the list of students attached to the classroom
* OPTIONALLY: view the actual progress of each student, in percentage% numbers or etc. (Possibly work for a future PR as I'm not sure if the Edu API has enough numbers to do the maths at the moment. I should check.)
WIP
> Signed In Classrooms View for Intro 2 Astro: Classrooms Details View (aka Single Classroom View aka Edit Classroom View)

- src/components/maps/CameraViewer.jsx
- src/components/maps/CameraViewerData.jsx
- src/components/maps/CameraViewerMetadata.jsx
- src/components/maps/CameraViewerPaging.jsx
- src/containers/maps/MapExplorer.jsx
- src/containers/maps/MapVisuals.jsx
- src/ducks/mapexplorer.js
- src/lib/wildcam-darien.mapConfig.js
- src/store/index.js
- src/styles/components/map-explorer.styl
* This PR adds the "Camera Viewer" functionality to the map.
* This means that a user can click on a Map Marker on the Map to view the camera trap photos from that specific camera.
* The Camera Viewer has a very basic pagination system. (Paging? Pagination?)
* Blurgh, we have a thumbnail generating system... but it only works if the photos are hosted on zooniverse.org, I think. I've built the thumbnailing functionality in, but it doesn't work with WildCam Darien's photos so... that Camera Viewer is blasting users with 6 hi-res images from the Darien National Park, scaled to tiny sizes. BLURGH, I say.
* I'm not sure if there's a Grommet/React ready pagination system we want to use - I saw the ToDo in the Classroom components but I'm unaware of a specific solution that we're aiming towards. …
> WildCam Darien Map part 5: Camera Viewer

- src/components/classrooms/ClassroomEditor.jsx
- src/components/classrooms/ClassroomsManager.jsx
- src/components/common/JoinPage.jsx
- src/components/layout/LoginButton.jsx
- src/containers/common/JoinPageContainer.jsx
- src/ducks/classrooms.js
This is a follow up on the new join page functionality. It's an improved UI and messaging for various states of joining. 
There may be still some API side issues with joining, but we're still working on debugging that and determining if it is EduAPI or Panoptes.
> UI clean up for classroom join page

- src/components/astro/AstroClassroomsTable.jsx
- src/containers/classrooms/ClassroomsTableContainer.jsx
- src/ducks/programs.js
- src/lib/config.js
- src/styles/components/classrooms-manager.styl
I've updated the placeholder for the project page links to now build out the URL. This is not totally functional yet because the actual user group id is not serialized on the classroom (see zooniverse/education-api#64).
I also fixed:
- the UI for the assignment fetching state
- Added a UI state if the project URL is unavailable 
- Made the program mocks available from the program duck to be usable in components for any if statements.
- Did a tiny bit of styling clean up
> Build URL for assignment project page

- src/components/classrooms/ClassroomsLayout.jsx
- src/components/common/JoinPage.jsx
- src/containers/classrooms/ClassroomEditorContainer.jsx
- src/containers/common/JoinPageContainer.jsx
- src/containers/darien/DarienRoutesContainer.jsx
This PR finishes a few remaining items left over from when the programs model was being development on the API:
- Fixes some programs requests
- Adds in the redirect for the Darien program when a student joins a classroom
- Fixes the sign in modal pop up on the join page if the user visits the page and isn't signed in
> Bug fixes join classrooms

- src/containers/classrooms/ClassroomEditorContainer.jsx
Fixes #81. I'll pull the comments in that issue about the views and shared API calls into a separate issue because it will be sometime we need to tackle for the Darien edit classroom view. 
I also fixed a couple of linter errors too.
> Fix edit classroom infinite loop

- package-lock.json
- package.json
Bumped to ZRC v0.7.0 to include the new responsive header.
> Bumped ZRC version to 0.7.0

- src/ducks/programs.js
Closes #28. Adds a helper function to alphabetically sort the programs by name before setting it to the redux store. This ensures consistent presentation.
> Add helper function to sort returned programs by name

- src/components/classrooms/ClassroomEditor.jsx
This just adds a nice message in the UI when no students have joined the classroom yet on the classroom edit page. @shaunanoordin since I know you're working on the WD version of this, it might be easier for you to cherry pick this change on to your working branch than to merge and rebase this.
> Message for edit view when no students

- src/components/common/SuperDownloadButton.jsx
- src/containers/astro/AstroClassroomsTableContainer.jsx
This is the transformation of the galaxy activity data export. I did a bit of refactoring of the hubble's law data transformation class method too and a small bug fix with the super download button.
> Galaxy data transform

- package-lock.json
- package.json
Update grommet to 1.9.0 and zoo-grommet to 0.3.0 that is now using 1.9.0 too.
> Update grommet and zoo-grommet

- src/components/common/Home.jsx
- src/containers/common/HomeContainer.jsx
- src/ducks/programs.js
- src/lib/config.js
- src/styles/components/home.styl
We didn't have a placeholder for the loading state for programs. This adds in a bit of UI placeholder while that's happening.
> Project card placeholders

- src/components/classrooms/ClassroomEditor.jsx
- src/containers/classrooms/ClassroomEditorContainer.jsx
- src/styles/components/classroom-editor.styl
Closes #101. This adds the toggle that the text on the classroom edit page says is there but wasn't yet. It just adds a button and some component state to toggle between showing a percentage or showing the actual counts per student for the assignments.
> Adds toggle for type of view for student assignment completion stat

- package-lock.json
- package.json
- src/containers/layout/AuthContainer.jsx
Temporary for #58 since I won't have time to fix the login with Google before the I2A demo.
> Bump ZRC version and hide google sign in button

- src/containers/astro/AstroClassroomsTableContainer.jsx
The code as it was written wasn't handling errors from the CSV parsing. This was found because the csv export from caesar was empty, so the parser errored.
> If the CSV parser errors, then better handle it

- src/containers/common/ProgramHomeContainer.jsx
- src/programs/darien/DarienProgram.jsx
- src/programs/darien/common/DarienNavi.jsx
- src/programs/darien/pages/DarienHome.jsx
- src/programs/darien/pages/info/DarienEducatorsIntro.jsx
- src/programs/gorongosa/GorongosaProgram.jsx
- src/programs/gorongosa/common/GorongosaNavi.jsx
- src/programs/gorongosa/pages/GorongosaEducators.jsx
- src/programs/gorongosa/pages/GorongosaHome.jsx
- src/programs/gorongosa/pages/GorongosaMap.jsx
- src/programs/gorongosa/pages/info/GorongosaEducatorsIntro.jsx
- src/programs/gorongosa/pages/info/GorongosaInfoEcology.jsx
- src/programs/gorongosa/wildcam-gorongosa.map-config.js
This PR adds two new features:
- WildCam Darien Lab now has an intro page for Educators.
- **WildCam Gorongosa Lab** has been introduced as a _hidden_ Program that's a WIP.
The Gorongosa Program is a near-identical clone of the Darien Program (also using the shared WildCam Lab components), and both Programs will now be developed in parallel. (See Dev Notes below)
@srallen please note that one common component was changed: `src/containers/common/ProgramHomeContainer.jsx` now has routes for WildCam Gorongosa Lab.
@mrniaboc please note that the WildCam Gorongosa Lab is only accessible by changing the URL slug to `#/wildcam-gorongosa-lab`
From this point on, I'll be developing WildCam Darien Lab and (a revamped) WildCam Gorongosa Lab **at the same time,** for Zooniverse Classrooms. This …
> WildCam Lab Classrooms - 2018 Rebuild - part 6

- src/modules/wildcam-classrooms/text.en.js
- src/modules/wildcam-classrooms/text.es.js
- src/modules/wildcam-classrooms/text.js
- src/programs/darien/pages/DarienHome.jsx
This PR finally hooks up the text system to a rudimentary translation system.
- Also, basic machine-translated Spanish text has been added.
Merging
> WildCam Lab Classrooms - 2018 Rebuild - part 11

- src/modules/wildcam-classrooms/components/AssignmentsListForEducators.jsx
- src/modules/wildcam-classrooms/components/AssignmentsListForStudents.jsx
- src/styles/components/wildcam-classrooms.styl
This PR adds a minor update to WildCam Darien Lab:
- Teachers can now see the progress of their students in each Classroom
- Classrooms now have expandable list that show student progress
Merging - apologies, this branch was actually live/deployed in late Sep/early Oct, but I forgot to merge it then. 😞
> WildCam Lab Classrooms - 2018 Rebuild - part 13

- src/modules/wildcam-classrooms/components/TeacherRegistrationForm.jsx
- src/modules/wildcam-classrooms/containers/WildCamForEducators.jsx
- src/modules/wildcam-classrooms/text.en.js
- src/modules/wildcam-classrooms/text.es.js
This PR now adds a Teacher Registration Form, allowing Teachers to submit (or edit) their Teacher-related meta-information, such as where they teach, what they teach, etc.
This form is available at `/#/wildcam-darien-lab/educators/register`, but there's currently no link for users to navigate to the form from the other pages.
Next:
- Add a link to the Register form
- In the Registration form, use checkboxes and radio boxes instead of text input boxes, for the appropriate fields.
Feature stable. Merging.
> Wildcam 2019 pt 3 - Teacher Registration Form

- src/modules/wildcam-classrooms/components/ClassroomsList.jsx
- src/modules/wildcam-classrooms/components/TeacherRegistrationForm.jsx
- src/modules/wildcam-classrooms/text.en.js
- src/modules/wildcam-classrooms/text.es.js
This PR improves the Teacher Registration Form available on WildCam Classrooms.
- the form is now accessible from WildCam Darien/Gorongosa > Educators > Classrooms > 'Register Teacher' button
- the form now uses checkboxes and radio buttons where appropriate.
Merging and deploying
> WildCam Lab 2019 pt 4 - Super Teacher Registration Form

- src/modules/wildcam-classrooms/components/AssignmentsListForStudents.jsx
- src/modules/wildcam-classrooms/components/ClassroomForm.jsx
- src/programs/darien/pages/info/DarienEducatorsIntro.jsx
- src/programs/gorongosa/pages/info/GorongosaEducatorsIntro.jsx
This PR addresses some minor updates requested by HHMI.
- ⚠️ Fix Teacher's Classroom's Assignment List not updating when changing between assignments.
- Fix some typos
WIP
> WildCam Lab 2019 pt6 - Minor Updates

- src/modules/wildcam-classrooms/components/ClassificationsDownloadButton.jsx
- src/programs/darien/wildcam-darien.classroom-config.js
- src/programs/darien/wildcam-darien.map-config.js
- src/programs/gorongosa/wildcam-gorongosa.classroom-config.js
- src/programs/gorongosa/wildcam-gorongosa.map-config.js
This PR addresses further comments from HHMI.
- WildCam Darien has been updated so its Map Explorer downloads no longer have the unused "carto_geom" and etc fields. 
- WildCam Gorongosa has been updated so its Student Assignments download and Map Explorer downloads work the same as Darien. 
Merging and deploying.
> WildCam Lab 2019 pt7 - Minor Updates

- src/components/astro/ExportModal.jsx
> Change messaging

- src/components/astro/AstroHome.jsx
Closes #165. Updates the URL for the instructor's guide to the URL in issue.
> Update URL for instructor's guide

- src/modules/wildcam-classrooms/components/ClassroomsList.jsx
- src/modules/wildcam-classrooms/containers/WildCamForEducators.jsx
- src/programs/darien/wildcam-darien.classroom-config.js
- src/programs/gorongosa/pages/info/GorongosaInfoAssignmentsGuide.jsx
- src/programs/gorongosa/wildcam-gorongosa.classroom-config.js
This PR updates some of the content for WildCam Gorongosa's Assignments Guide (both the page and the popup).
The Assignments Guide page is actually lacking 7 images, since the currently provided content exceeds acceptable sizes (GIFs that are > 1MB). These can be added at a later date should better images be acquired.
Ready to go
> WildCam Lab 2019 pt10 - WildCam Gorongosa Lab Assignments Guide

- src/ducks/auth.js
- src/modules/wildcam-classrooms/components/AssignmentsListForStudents.jsx
- src/modules/wildcam-classrooms/components/StatusBorked.jsx
- src/modules/wildcam-classrooms/ducks/index.js
This PR improves the information provided by status messages.
- for WildCam Lab programs, errors within the lab components provide more error information.
- for all programs, the Authentication system provides a bit more error information.
Also,
- WildCam Lab's Student Assignments List now triggers a fetch only when it detects the Classrooms data has been _successfully_ fetched. Without this minor reordering of actions, the Assignments will attempt to fetch _before_ Classrooms would finish fetching, leading to a quirk where the "loading" message wouldn't show. (The Assignments data is otherwise retrieved just fine, it only affects the visual UI.)
Ready to go; tagging @srallen FYI, since there's a minor change to `src/ducks/auth.js`'s `handleError()` code
> Better Status Messages

- Dockerfile
- README.md
- docker-compose.yml
- webpack.config.js
quick and easy development via docker
> add dev docker setup

- src/components/astro/AstroClassroomsTable.jsx
Adds button to make it easier for educators to share with students.
> Add button to copy project link url

- src/components/astro/AstroHome.jsx
New instructor's guide for I2A.
> Update instructor's guide link

- src/components/astro/AstroClassroomsTable.jsx
- src/ducks/assignments.js
- src/ducks/programs.js
I've added some code to be able to test this on the staged deploying (using production env). All changes but the updated mock will need to be reverted once the production database is updated. I'll open a subsequent PR after merging this one for the changes for later merging and deployment.
> New Galaxy Zoo classrooms project

- src/components/astro/AstroClassroomsTable.jsx
- src/ducks/assignments.js
- src/ducks/programs.js
This is to remove the code added in #187 to be able to test on the preview site. Merge and deploy this after the final production database is updated with the necessary changes.
> Remove code added for testing

- package-lock.json
- package.json
Updating dependencies based on audit report.
> NPM audit fix

- docs/wildcam/google-drive-api/privacy.md
This is so we can apply for verification and remove the 100 user cap.
> Privacy policy for Google Drive API integration

- package-lock.json
This is a straightforward npm audit fix for updating dependencies.
> NPM audit fix - Nov 2020

- src/components/GlobalNotification.jsx
Context: https://github.com/zooniverse/operations/issues/459 has been fixed!
This PR updates the global notification so users know that the Sign In issues have been resolved.
I'm going ahead and merging + deploying this. Reminder to self: REMOVE Global Notifications altogether after 2 weeks-ish.
> Update message for solved Sign In issues (Dec 2020)

- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
this pr specifies a working az cli version to avoid this issue https://github.com/Azure/azure-cli/issues/20154
Linked to https://github.com/zooniverse/Panoptes-Front-End/pull/6044
> Fix az deploys

- package-lock.json
- package.json
- webpack.production.config.js
An update to `ImageMinimizerPlugin` broke the production webpack build. This updates the plugin config to match the latest version.
> Fix broken production build

- .github/workflows/build_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
- package.json
- refactor build scripts, primarily so staging uses `webpack.production.config.js`
- updates GitHub workflows for new build scripts
> Refactor build scripts

- src/components/layout/AppHeader.jsx
- src/containers/common/ProgramHomeContainer.jsx
- src/ducks/programs.js
per #318 and feedback edit slug/url to `activities-for-undergraduates`
> Edit Activities for Undergraduates slug

- src/programs/kenya/pages/info/KenyaInfoCSV.jsx
This PR adds content to the previously empty Data Guide page: https://classroom.zooniverse.org/#/wildwatch-kenya-lab/explorers/data-guide/
Merging & deploying.
> Wildwatch Kenya Lab: update Data Guide

- package-lock.json
- package.json
- src/modules/wildcam-classrooms/components/ClassificationsDownloadButton.jsx
Tweaking the dependencies to see if anything can fix the build issues. See #351 and https://github.com/zooniverse/classroom/actions/runs/2471180988
> June 2022: npm audit fix

- package-lock.json
- package.json
No substantive changes, fixes versioning issue.
> Upgrade to Zooniverse-React-Components v0.9.6

- README.md
- src/components/activitiesForUndergrads/ActivitiesForUndergradsHome.jsx
Adds ASTRO/GEO 101 Planet Four button link to materials and course description.
> Add ASTRO/GEO 101 Planet Four content

- src/modules/wildcam-map/containers/MapVisuals.jsx
Follows #479 
This PR is a minor refactor of the Map Explorer component, used in the map sections of WildCam-style Programs (Gorongosa, Darien, Kenya).
- The Leaflet upgrade to 1.9 (which is in preparation for 2.0) made notes about tree-shaking, and is trying to reduce the use of the global `L` used by classic Leaflet code.
- That's exactly what we're doing here.
Functionality remains the same. Please see 479 for a checklist of expected map functionality.
> Map Explorer: reduce use of Leaflet's global L

- src/containers/common/ProgramHomeContainer.jsx
- src/programs/zooniverse-in-schools/ZooInSchoolsProgram.jsx
- src/programs/zooniverse-in-schools/pages/HomePage.jsx
- src/programs/zooniverse-in-schools/pages/ResourcesPage.jsx
Part of: 2023's "Zooniverse in Schools" project, which brings Zooniverse-based education tools to classrooms with younger students.
This PR adds pages for the upcoming new **Zooniverse In Classrooms** Program.
- URL will be https://classroom.zooniverse.org/#/zooniverse-in-schools
- There's a home page, and a Resources page, mostly with placeholder text.
- This Program is mostly a content page for educators, similar to the [Activities for Undergraduates](https://classroom.preview.zooniverse.org/#/activities-for-undergraduates) Program.
Several additional actions are required to get this Program running, but that's outside of the scope of this PR. This includes:
- Adding Zooniverse In Classrooms as a new Program in the Education API
- Making several changes to Astro 101, since that's linked …
> Zooniverse In Classrooms: Initial Pages

- src/components/common/Home.jsx
- src/containers/common/ProgramHomeContainer.jsx
- src/ducks/assignments.js
- src/programs/zooniverse-in-schools/ZooInSchoolsProgram.jsx
- src/programs/zooniverse-in-schools/pages/HomePage.jsx
- src/programs/zooniverse-in-schools/pages/ResourcesPage.jsx
New Program: Zooniverse In Schools
Associated Stakeholders: Kat O'Brien Skerry
This PR adds a new education Program to Classrooms.
Added in this PR:
- New Program home page: https://classroom.zooniverse.org/#/zooniverse-in-schools
- Resource page: https://local.zooniverse.org:3998/#/zooniverse-in-schools/resources
- Content is mostly a placeholder
- **Astro 101** modified slightly:
- Each Astro 101 classroom can now display 3 or more Assignments.
- (TMP) Home page: Zooniverse In Schools is **hidden** from the public, unless the page is viewed with `?preview=true`
External changes required:
- Zooniverse In Schools project added to Zooniverse
- Basically a copy of the existing [Galaxy Zoo 101](https://www.zooniverse.org/projects/mollysimon/galaxy-zoo-crowdsourcing-activity) zooniverse …
> New Program: Zooniverse In Schools

- src/programs/zooniverse-in-schools/pages/ResourcesPage.jsx
Program: Zooniverse In Schools
This PR is a content update, adding links to PDF and video resources to the Program's Resource page: https://classroom.zooniverse.org/#/zooniverse-in-schools/resources
External actions:
- two PDFs added as the Zooniverse shared Google Drive, with public share links
- two videos added to the [Zooniverse YouTube channel](https://www.youtube.com/@the_zooniverse)
> Zooniverse In Schools: add links to PDF and Video resources

- src/programs/zooniverse-in-schools/pages/HomePage.jsx
- src/programs/zooniverse-in-schools/pages/ResourcesPage.jsx
Program: Zooniverse In Schools
This is a minor content update for ZIS.
External updates:
- PDF files on [Shared Google Drive folder](https://drive.google.com/drive/folders/1kYpyw2ay-KhS4eN_jes1VdMx3rNBvxjt) updated (requires Zooniverse access, though I'm trying to get this folder publicly shared)
> Zooniverse In Schools - 30 Jan 2023 update

- src/components/common/Home.jsx
- src/components/layout/AppHeader.jsx
- src/programs/zooniverse-in-schools/pages/HomePage.jsx
Program: Zooniverse In Schools (with some WildWatch Kenya)
ZIS is now going live. This PR makes the following changes:
- ZIS now appears on the Classrooms home page
- ZIS now appears on the Header Navi
- WWKenya also appears on the Header Navi. I forgot to add this Program up there much much earlier
- NOTE: I may have to reconsider the design for the header navi, it's growing way too big
- ZIS's "Intro Video" link now reads "Coming Soon" instead of "Placeholder"
There's another update that needs to be made - the Edit Classroom page of Astro101 needs to display the third assignment - but that's for a separate PR since that'll involve a bit of work.
Ready to go!
> Zooniverse In Schools - 31 Jan 2023 Update (go live)

- src/programs/zooniverse-in-schools/pages/HomePage.jsx
- src/programs/zooniverse-in-schools/pages/ResourcesPage.jsx
Program: Zooniverse In Schools
This is a standard content update.
- Home page's link to Astro 101 had its text clarified.
- Links on Resources page appended with "Activity numbers". (Note to self: once finalised, consider a better way to organise the page.)
- New mailto: link added to Home page.
External changes:
- "Introduction" PDF file updated. (Surprise! Google Drive allows you to replace a file with a newer version, and the share link won't change. Drive doesn't treat the newer version as a different file, which I could have sworn was what it did previously to my personal files.)
- "Additional Hands-on Activities" PDF [added.](https://drive.google.com/file/d/1e8K74sJiyEhKpZ9kFRLIIXL9wZ_7ZOxm/view?usp=sharing)
> Zooniverse In Schools - 9 Feb 2023 update

- .github/workflows/build_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
- Dockerfile
- package.json
- update `package.json`.
- update Dockerfile.
- update GitHub workflows.
> Build with Node 18 (lts/hydrogen)

- src/programs/zooniverse-in-schools/pages/HomePage.jsx
- src/programs/zooniverse-in-schools/pages/ResourcesPage.jsx
Program: Zooniverse In Schools
This PR is mostly a content update.
- Introductory Video added: https://youtu.be/5xhNIw3R5z4
- External links now have rel="noopener noreferrer" as standard.
> Zooniverse In Schools - 20 Feb 2023 update

- package-lock.json
- package.json
These are just a bunch of dependency bumps, following security updates for PJC and ZRC.
> Maintenance Update (Mar 2025 version)
