zooniverse/classroom

src/components/Home.jsx
src/config.js
src/index.jsx

* This PR adds the ability for the app's `config` settings to change depending on the environment it's in.
* e.g. instead of using `config.dev.foobar` to get the 'foobar' config value, we just need to use `config.foobar`
* We can manually switch the environment by passing a query string, e.g. `localhost:3998?env=production` - same concept as the Panoptes JavaScript client.
* This code was based on the Panoptes JavaScript client - any suggestions for improvements are welcome.
* The switching supports three environments - production, development and staging - but...
* [Quirk?] ...that last one might be a head-scratcher, given my recent problems with environmental variables. I can only run `npm start` when my `NODE_ENV` is set to `development`, yet when the app runs, the variable …

Environment-dependent Config settings

---

package.json
src/index.jsx

This PR switches to React-Router v4's `HashRouter` component to use hash history instead of browser history. This is to make directly browsing to say `/#/astro` work in the browser. To get direct browsing to `/astro` with browser history working requires configuration setup with the server, which we could do, but I don't really see any reason to do that unless 100% clean urls are asked for.

Use hash history router instead of browser history

---

src/index.jsx

As discussed in slack and noted at https://github.com/zooniverse/rfc/issues/16#issuecomment-321005098, the app is reverting back to using browser history so that we can dynamically set the environment with a url query param. We'll need to configure our hosting server to be able to correctly route urls if directly browsed to.

Switch back to BrowserRouter.

---

package-lock.json
package.json
src/components/Home.jsx
src/components/astro/AstroHomeSignedIn.jsx
src/containers/common/ClassroomManagerContainer.jsx
src/ducks/classrooms.js
src/ducks/reducer.js
src/index.jsx
src/lib/config.js
src/lib/edu-api.js

This is WIP PR of an initial setup of a duck for classrooms (using jumpstate conventions and helpers on top of redux) and using superagent with the superagent-jsonapify plugin. I moved the `config.js` file into a lib folder with another helper js file for the api calls. `edu-api.js` has some default headers and sets up the superagent-jsonapify plugin too. At some point, maybe not for the Sept 1 target date, but we could abstract out helper methods into this file to dry up some of the API calls. 
I didn't quite get this working as there are still some issues with staging. I've started on UI components on a separate branch, but thought I'd get an example of this up for you to look at first.

Example use of superagent with classrooms get request

---

package-lock.json
package.json
src/components/common/ClassroomCreateForm.jsx
src/components/common/ClassroomManager.jsx
src/containers/common/ClassroomCreateFormContainer.jsx
src/containers/common/ClassroomManagerContainer.jsx
src/ducks/classrooms.js
src/index.tpl.html
src/styles/components/classroom-manager.styl

What this PR does:
- A few improvements to the classroom management table to get closer to the design
- Copy link functionality for the classroom join link
- Adds the Toast grommet component to show success of copying the join link. This component could be used to notify success of classroom creation and other actions. It auto-closes on its own. This is instead of the Notification component which has to be dismissed and is much larger in visual space. I'm open to using either/or/both, so let me know your thoughts. 
- A non-functional UI for the classroom create form. You can view it by clicking on the "Create Classroom" button
This can all be tested by using zootester1 using production database. 
Next steps are more style improvements and making the create form functional.

Classroom create form, improved styles, and copy link functionality

---

src/components/astro/AstroClassroomManager.jsx
src/components/common/ClassroomCreateForm.jsx
src/components/common/ClassroomManager.jsx
src/containers/common/ClassroomCreateFormContainer.jsx
src/containers/common/ClassroomManagerContainer.jsx
src/ducks/classrooms.js
src/lib/edu-api.js
src/styles/components/classroom-manager.styl

This PR finishes the functionality for the create action as well as adds a delete button to the classroom list and the delete functionality.
- Improved UI for the create form modal
- A jumpstate Effect for getting classrooms and their linked assignments. This makes this sequence of API calls available to the whole app which is useful both for the delete method managed by the `ClassroomManagerContainer` and the create method managed by the `CreateClassroomFormContainer`.
- Related to the new Effect is a question about API usage optimization. We may want to consider alternatives to requesting for all classrooms again after create and delete. I left inline comments specifically about what I mean.
- Added `post` and `httpDelete` helper functions

Create form functionality and delete action

---

package-lock.json
package.json
src/components/common/SuperDownloadButton.jsx
src/components/maps/MultiChoiceFilter.jsx
src/containers/maps/MapControls.jsx
src/ducks/mapexplorer.js
src/lib/mapexplorer-helpers.js
src/lib/wildcam-darien.mapConfig.json

* This PR adds the ability for users to download the data they're viewing on the map (i.e. with whatever species/habitat/etc filters they've selected) as a CSV file.
* Notably, this is done using the new `SuperDownloadButton` component, which basically rips off most of the code from WildCam Gorongosa to make it functional across all browsers.
* Yes, especially Safari, which was such a strong requirement that we had to make a wonky echo-ing workaround using the EduAPI.
* That said, the SuperDownloadButton does less work this time round, as it doesn't need to convert GeoJSON data into CSV as it previously did. (The Carto API handles that this time, woo) 
* The `<SuperDownloadButton>` is bizarre in that it crams multiple sub-elements into a Grommet `<Button>` and I'm not entirely sure how …

Wildcam Darien Map part 3: Download Button

---

package-lock.json
package.json
src/components/astro/AstroHome.jsx
webpack.production.config.js

* Thanks to Adam, we now have a production-ready site at https://classroom.zooniverse.org
* classroomS.zooniverse.org will also redirect to the site.
* There are NO auto-deploys for this project. (At least not in this phase.)
* The S3 bucket is `zooniverse-static/classroom.zooniverse.org`
* There will be NO URL rewriting, (e.g. no classroom.zooniverse.org/astro) since we're using hash routing (e.g. classroom.zooniverse.org/#/astro). We may revisit this in the future, but for now this is how we're rolling, up for launch.
* As with most PJC-using projects, we can switch environments using `?env=production`
* This PR allows us to manually deploy our project to classroom.zooniverse.org using `npm run deploy-production`
* It works. Mostly? Kinda?
* I mean, https://classroom.zooniverse.org now …

Manual Deploy Script

---

.babelrc
package.json

For #34  (maybe fix?)
I haven't actually tried the deployment, but the build looks good.
- ExtractTextPlugin isn't needed for the css-loader configuration because the css files are imported into the main.styl file which is then transpiled by the stylus configuration and that will handle extraction to main.css. I think this is something that needs fixing in zoo-reduxify too.
- I fixed the environment variable exports in the npm scripts. I added the export command so that the variable is put into your bash profile. Not sure if this will fix the production env when deployed since I didn't try that. But I noticed that now the webpack configuration file seems to be correctly running in production with the build task.
- I removed the redundant script in the deployment script and calling `npm …

Export env variables. Add plugin to babel production env.

---

src/lib/config.js

* Without this PR, when you go to http://localhost:3998 and log in as `zootester1`, you'll see _no_ Classrooms listed under the Intro2Astro section.
* In the console, you'll notice several 502 errors indicating the necessary Classroom/EduAPI resources could not be reached.
* This PR fixes the issue by changing the URL for the Education API (Staging version) to the correct value.
* To confirm, go to http://localhost:3998, log in as `zootester1` (on the Panoptes _Staging_ login screen), and you'll see at least one pre-made Class and Assignment there. (Star Wars, FYI.)
* You should see NO 502 Gateway errors in the console.
NOTE: This fix was also contingent on the Panoptes Staging doorkeeper system being set up properly. Should be irrelevant to this PR since the setup works perfectly, but …

Fix Education API URL for Staging

---

src/components/maps/MultiChoiceFilter.jsx
src/components/maps/SimpleMapLegend.jsx
src/containers/maps/MapVisuals.jsx
src/lib/wildcam-darien.mapConfig.js
src/lib/zooniversal-translator.es.js
src/styles/components/map-explorer.styl

* This PR adds the 'region' layers to the map.
* Notably: the park boundaries for the two national parks, and the areas of vegetation.
* These layers can be controlled by the 'Layers' control on the top-left corner of the Map.
* This map has no legends. It could probably use some?
* The layer order is fairly random? So sometimes the Data (camera map markers) layer is below the park boundaries, which isn't what we want? 
Ready for review, but it'll make more sense to merge PR #39 and #40 first, then review & rebase this branch onto the new master.

WildCam Darien Map part 7: Regions

---

src/components/astro/AstroClassroomsTable.jsx
src/components/classrooms/ClassroomsManager.jsx
src/containers/classrooms/ClassroomFormContainer.jsx
src/containers/classrooms/ClassroomsManagerContainer.jsx
src/containers/classrooms/ClassroomsTableContainer.jsx
src/containers/common/ProgramHomeContainer.jsx
src/containers/layout/AppNotification.jsx
src/ducks/assignments.js
src/ducks/classrooms.js
src/ducks/programs.js

This is a WIP branch to eventually close #55. This adds the `createAssignment` Effect in the assignment duck as well as some code to auto-create assignments if the program (like I2A) needs to do that. Right now I have some mocks for programs, but we should create these on the staging server. I'm planning on storing a lot of information in the metadata object on the program to keep track of the data needed for the assignments that will be auto-created.
It also should be noted, I branched this off of the `programs` branch, so this will need a rebase as soon as #52 is merged.
I'm not sure if this works yet as there's been issues with the education-api-staging server again this past week that hopefully will be addressed next week (noted in the slack channel; likely issue on docker swarm?). …

Auto create assignments

---

package-lock.json
package.json
webpack.production.config.js

The webpack production configuration was missing the plugin to copy static asset files. I've added `CopyWebpackPlugin` as a dependency and the configuration to the plugin option in the production configuration.
This can be tested by running the build on its own, `npm run build` and checking the `dist` folder for the images.

Fix deployment of images

---

src/components/astro/AstroClassroomsTable.jsx
src/components/classrooms/ClassroomsManager.jsx
src/containers/classrooms/ClassroomEditorContainer.jsx
src/containers/classrooms/ClassroomsManagerContainer.jsx
src/containers/classrooms/ClassroomsTableContainer.jsx

I think this was a regression that came in with #56. In the reorganization I did, I think I accidentally removed the `ConfirmationDialog` used with the classroom delete button.
I did some minor improvements with the success handling of the delete requests for both classroom and student. We only want to show the success message if there's a response from the API.

Fix regression with ConfirmationDialog on classroom delete

---

src/components/astro/AstroClassroomsTable.jsx
src/components/classrooms/ClassroomEditor.jsx
src/components/common/GenericStatusPage.jsx
src/containers/common/HomeContainer.jsx
src/containers/common/ProgramHomeContainer.jsx
src/ducks/programs.js

Closes #49. We now have I2A and WD: Lab programs on the staging database. We can request them using the API. Note: the API show route for the programs is still authenticated, so you have to be logged in for this to work. I've opened zooniverse/education-api#69 about it.
Also, another idea on clearly communicating status: I've created the `GenericStatusPage`. This is a fall back page to show in case the server is down or the load time is really slow. I'm thinking some teachers may bookmark the I2A or Wildcam page and directly navigate to those pages. In case the status is still 'fetching' or 'error', The GenericStatusPage will display.
However, we have a lot of ways of communicating status. From Grommet's Toast and Notification components to now this. I may be going overboard with it.

Request programs

---

src/containers/classrooms/ClassroomFormContainer.jsx
src/containers/classrooms/ClassroomsManagerContainer.jsx
src/ducks/assignments.js
src/ducks/classrooms.js

For #72 and #54, this PR refactors the methods for creating a classroom and auto-creating the assignments for I2A classrooms. 
- Classroom creation now includes the program id in its relationship. This is to support filtering classrooms by program
- Auto-create assignments no longer needs the program id and the workflow id is sent in the attributes
This isn't fully working yet because of an API bug that is fixed in zooniverse/education-api#70 still needs to merge.

Classroom program link

---

src/components/astro/AstroClassroomsTable.jsx
src/components/classrooms/ClassroomsManager.jsx
src/components/darien/DarienClassroomsTable.jsx
src/components/darien/DarienHome.jsx
src/containers/astro/AstroClassroomTableContainer.jsx
src/containers/astro/AstroClassroomsTableContainer.jsx
src/containers/classrooms/ClassroomFormContainer.jsx
src/containers/classrooms/ClassroomsManagerContainer.jsx
src/containers/classrooms/ClassroomsTableContainer.jsx
src/containers/common/ProgramHomeContainer.jsx
src/containers/darien/DarienRoutesContainer.jsx
src/ducks/classrooms.js
src/styles/components/classrooms-manager.styl

This will have to merge after #73 because it is using the program filter for classrooms, so please ignore the changes that pertain to #73 until this is rebased.
This adds a view for the Darien educators page which is basically the classrooms manager which toggles between the table list view or the classroom editor. Darien's table will be slightly different than I2A's:
- the ability to create and edit assignments which I imagine will open a modal with a form like classroom create/edit does. Right now I just have placeholder buttons for creating and editing an assignment in the markup.
- The actual data in the table for the assignments. I replaced the export data column for the due date. 
I _really_ wanted to try to be clever with determining which classroom table to display by trying out …

Darien classrooms table

---

src/components/classrooms/ClassroomForm.jsx
src/components/darien/DarienClassroomsTable.jsx
src/containers/classrooms/ClassroomFormContainer.jsx
src/containers/classrooms/ClassroomsTableContainer.jsx
src/ducks/assignments.js
src/ducks/classrooms.js
src/ducks/programs.js
src/index.tpl.html

This does two things:
- Fixes a possible regression I introduced that I noticed while debugging #74 
- The classroom create/edit form wasn't clearing out the form fields on unmount, so when you created a classroom and then clicked to create another (or edit), the form field had the previous content.
- This also adds a consistent sort order for the I2A assignments

Fix classroom form state

---

src/components/Main.jsx
src/containers/common/ProgramHomeContainer.jsx

The route for the join classroom page was broken. The `Switch` component was supposed to be handling the matching order and I thought the join page would be matched first, but the redirect was for some reason. I don't understand, but moving the join route up a level fixed it.

Move route for join page up a switch statement

---

src/ducks/programs.js

This updates the error handler for requesting the programs. If it 404s, like it currently does in production since the back end API hasn't been deployed yet and still has no notion of a program, then it'll fallback to the programs mocks.

Use program mock as fallback

---

src/components/Main.jsx
src/components/astro/AstroClassroomsTable.jsx
src/ducks/assignments.js
src/ducks/classrooms.js
src/ducks/programs.js

It's been decided that the introductory assignment wasn't a good fit for use of the Zooniverse's project builder and platform. This PR removes it. WIP because staging API is on the fritz at the moment and the programs in the database still need updating. I also fix a typo and make the classifications_target a string since that's what they actually are on assignments. I fixed this in #76, but this is a better fit for updating this. I'll rebase #76 after this merges.

Remove intro assignment

---

src/components/astro/ExportModal.jsx
src/components/classrooms/ClassroomEditor.jsx
src/components/common/SuperDownloadButton.jsx
src/containers/classrooms/ClassroomEditorContainer.jsx
src/containers/maps/MapControls.jsx
src/ducks/assignments.js
src/ducks/classrooms.js
src/lib/file-download-helpers.js
src/lib/mapexplorer-helpers.js

For #67, in anticipation of using real stats for the student's progress, this PR
- Extracts `blobbifyData` and `generateFileName` into its own helper js file to be shared between Darien and I2A
- Removes the Introduction assignment from the table since that won't be a Zooniverse project now
- Makes the download csv file name prefix a prop for the SuperDownloadButton
- Fixes the TypeError seen on the classroom edit page when assignments were requested
- Fixes linter errors in SuperDownloadButton
Question about the SuperDownloadButton:
We officially only support the current version and last previous version of browser. For Safari, that's now version 10 and 11. Do we still need the work around written in the SuperDownloadButton for Safari?

Real stats prep

---

src/components/classrooms/ClassroomEditor.jsx
src/containers/classrooms/ClassroomEditorContainer.jsx

To be merged after #90. This closes #50. It finishes the export stats class method for the individual classroom edit view. Note: I've renamed the button and method to `Export Stats` and `exportStats` because I think we should avoid saying grades anywhere. As a former IT person who worked for a couple of Universities, even implying we store grades could make us vulnerable to complying with student privacy laws. It's up to the teacher if they want to use these stats in their grading, but they aren't grades.

Export stats

---

package-lock.json
package.json
src/components/astro/AstroClassroomsTable.jsx
src/components/astro/ExportModal.jsx
src/components/classrooms/ClassroomEditor.jsx
src/components/common/SuperDownloadButton.jsx
src/containers/astro/AstroClassroomsTableContainer.jsx
src/containers/classrooms/ClassroomEditorContainer.jsx
src/ducks/assignments.js
src/ducks/caesar-exports.js
src/ducks/programs.js

For #26, this is a step forward in getting the caesar requests to work. The 404 we saw before was a red herring. It didn't actually work, for one, because the reduction type data export wasn't available publicly before. This is now fixed and Intro2Astro workflows have public caesar exports.
This PR fixes the POST to create the export, stores the pending export in the redux store and if requested again, checks against the presence of a pending export. If there is a pending export, we request using its id. 
There are a few issues still needing resolving, such as, how do we best check for a pre-existing export so we don't unnecessarily create new exports. Because of the remaining API/UX questions, there are still a few logs and commented out items.

Update caesar requests

---

src/components/astro/AstroClassroomsTable.jsx
src/components/astro/ExportModal.jsx
src/components/astro/GoogleDriveExportButton.jsx
src/components/common/SuperDownloadButton.jsx
src/containers/astro/AstroClassroomsTableContainer.jsx
src/ducks/caesar-exports.js

This closes #26 and should merge after #95. 
I've refactored the Papaparse function to be wrapped in a promised and moved it into the `AstroClassroomsTableContainer`. I've also refactored the export to Google drive to use the actual transformed CSV data. The UI received some improvements including status messages about the export and the modal will remain open to offer a link to open the CSV in Google Sheets. I'm a bit unsure with this UI state since I'm showing two success messages: one that an export from caesar is available, and the other is that the CSV successfully exported to Google Sheets and the URL link. 
Still to do: The CSV transformation for the galaxy zoo project.

Finished google export function

---

package.json
src/components/astro/AstroClassroomsTable.jsx
src/components/classrooms/ClassroomEditor.jsx
src/containers/assignments/AssignmentFormContainer.jsx
src/ducks/assignments.js
src/ducks/auth.js
src/ducks/programs.js
src/lib/config.js
webpack.config.js

This preps the assignment creation for Wildcam Darien including:
- Setting up a staging environment variable
- Adding the hard coded workflow ids and sample subjects to WD and WG program mocks
- Checking for the staging environment and using the appropriate hard coded workflow and sample subject ids if it applies on assignment create
- Updates propTypes where needed
This also includes some fixes for the join link and a deploy to staging npm script. I've already deployed to staging via a different branch because I wanted the I2A instructors to start to test features for me this week on staging. The staging environment update and script were cherry picked on to this branch to come in with this PR. 
Note that the assignment create still doesn't work due to noted permissions issue in the …

Assignment create

---

src/components/astro/AstroHome.jsx
src/components/classrooms/ClassroomEditor.jsx
src/components/classrooms/ClassroomForm.jsx
src/components/classrooms/ClassroomsManager.jsx
src/styles/components/classroom-editor.styl
src/styles/global/buttons.styl

Grommet should be handling the hover and focus styles, but I think there's a bug when the button is the child of several Box components that have background color index props set. This adds some styles to make sure the buttons get hover and focus styles.

Fix button hover and focus styles

---

src/containers/astro/AstroClassroomsTableContainer.jsx

I was concatenating strings rather than doing actual addition with integers. This fixes the total classification count for the galaxy activity export.

Convert strings to int

---

src/ducks/programs.js

Removes using the mocks on 404 for the programs request. This was used previously for demo purposes while production didn't support programs yet.

Remove using program mock in state on 404

---

src/components/astro/AstroClassroomsTable.jsx
src/components/classrooms/ClassroomEditor.jsx
src/components/classrooms/ClassroomForm.jsx
src/containers/classrooms/ClassroomEditorContainer.jsx
src/containers/classrooms/ClassroomFormContainer.jsx
src/ducks/programs.js

This is a collection of minor tweaks:
- Updates the percentage stat for assignment completion to use rounded numbers
- Updates the production I2A program mock to correctly reflect what it is on the db
- Consistently uses the formField prop types and prop name with the `ClassroomEditor`
- Uses null for the `ClassroomEditor` form's `onSubmit` if the status is creating. I'm not sure if this totally works yet because production is having random 500s right now, which only happens after a request times out after a few seconds. I want to disable the submit button if there's a pending POST and the Grommet Button is only disabled if the onClick handler is null. I'm not sure if this is true for the handler set for the form on the Form component. We might need to move the event handling to the …

A few minor I2A tweaks

---

src/components/astro/ExportModal.jsx

Pretty much what this says: This adds the button to request another new export if the response is either the failed state or no exports exist from caesar.

Add button to request new export to failed or no export status message

---

src/components/common/Status401.jsx
src/components/common/Status404.jsx
src/components/darien/Darien401.jsx
src/components/darien/Darien404.jsx
src/components/darien/DarienClassroomsTable.jsx
src/components/darien/DarienEducators.jsx
src/components/darien/DarienHome.jsx
src/components/darien/DarienMap.jsx
src/containers/common/ProgramHomeContainer.jsx
src/containers/darien/DarienProgram.jsx

This PR plans to improve the WildCam Darien Lab's Classrooms and Assignments.
Goals:
- Only logged-in users can access Educators page (i.e. Classroom & Assignment management.) ( fixes #91 )
- Non-logged-in users have access to a limited subset of pages and are prompted to login.
- Educators can create & edit _Darien-specific_ Classrooms.
- Educators can create & edit _Darien-specific_ Assignments.
- [major][ambitious] Educators can select Subjects from the Map Explorer to create Assignments. _(EDIT: maybe start with empty Assignments first?)_
Expected BIG STUFF that needs handling:
- Darien-specific Classroom & Assignment management will run head-long into the points discussed in #85 , since I'll need to address the hardcoded I2A things in the common Classrooms components. 
NOT in the …

Darien Classrooms & Assignments Mk2 - Part 1

---

src/components/astro/AstroClassroomsTable.jsx
src/components/classrooms/ClassroomEditor.jsx
src/containers/classrooms/ClassroomEditorContainer.jsx

Closes #100 and fixes a bunch of stats math I did wrong. 
- When you want to round to two decimal places, you use `toFixed()` not `Math.round()` 🤦‍♀️ 
- Fixes percentages on the classrooms table view. I was using the classroom's classification count instead of the sum of the individual student's assignment's counts.
- Just display 100% even if the student does more classifications than assigned
- Fixes a regression with the Export stats button
- Disables the Export Data button if there are no classifications (#100)
How to test manually:
I had to already deploy this branch to production because the lambdas to do the counts on staging isn't setup. This should be ok because no one is really using the production site yet.
- Log in as zootester1
- You should see an I2A classroom "A classroom …

Fix all the stats math

---

src/components/common/ProgramHome.jsx
src/containers/common/ScrollToTopOnMount.jsx

This adds a scroll to top component to handle this behavior when desired as documented in the RR v4 docs. I added it to the ProgramHome component because it makes sense there. It can be added elsewhere as needed.

Use scroll to top behavior when program home is mounted

---

src/ducks/caesar-exports.js

This adds the `processing` state for caesar exports to the pending filter to use the same message as displayed for the pending state.

Show the same message as pending for exports in the processing state

---

src/modules/wildcam-classrooms/components/ClassroomForm.jsx
src/modules/wildcam-classrooms/components/ClassroomsList.jsx
src/modules/wildcam-classrooms/containers/WildCamClassrooms.jsx
src/modules/wildcam-classrooms/ducks/index.js
src/modules/wildcam-map/ducks/index.js
src/programs/darien/pages/DarienEducators.jsx
src/styles/components/wildcam-classrooms.styl

This PR follows PR #122 . In this PR, the WildCam-type Program's Classroom management has been rebuilt, with a focus on managing state/view transitions and messaging users.
Major Updates
- The `WildCamClassrooms` component now allows Teachers to create, edit, and delete classrooms.
NOT YET BUILT
- Teachers cannot yet manage students in each Classroom.
- Teachers cannot yet create Assignments (selecting photos from the WildCam Map Explorer) and assign students to them.
Merging, part 3 coming.

WildCam Lab Classrooms - 2018 Rebuild - part 2

---

src/ducks/classrooms.js
src/ducks/programs.js
src/lib/edu-api.js
src/modules/wildcam-classrooms/components/AssignmentForm.jsx
src/modules/wildcam-classrooms/components/StudentsList.jsx
src/modules/wildcam-classrooms/components/SubjectsList.jsx
src/modules/wildcam-classrooms/containers/WildCamClassrooms.jsx
src/modules/wildcam-classrooms/ducks/index.js
src/modules/wildcam-map/containers/MapControls.jsx
src/modules/wildcam-map/ducks/index.js
src/programs/darien/DarienProgram.jsx
src/styles/components/wildcam-map.styl

This PR follows #124. In this PR, we're mostly concerned with fixing bugs that prevent the Teachers from fully enjoying the Create/Edit WildCam Assignments functionality.
Updates in place:
- You can actually edit WildCam Assignments. There was a bug previously that prevented data from being saved on an update. (Create Assignment continues to work fine.)
Planned updates:
- The Assignment form should remember any data the user type into the form before they transition to the Map (to select Subjects). At this moment, if you type in an Assignment name, select subjects, then return, the Assignment name just goshdarn disappears/resets to the original.
@srallen please be aware that I've updated the `/lib/edu-api.js`'s `put()` function, since the pre-built request body structure wasn't flexible …

WildCam Lab Classrooms - 2018 Rebuild - part 4

---

src/programs/darien/DarienProgram.jsx
src/programs/darien/common/DarienNavi.jsx
src/programs/darien/pages/DarienEducators.jsx
src/programs/darien/pages/DarienHome.jsx
src/programs/darien/pages/info/DarienInfoEcology.jsx
src/styles/components/program-navi.styl
src/styles/components/wildcam-info-page.styl

This PR adds a number of content-focused features to the WildCam _Darien_ Lab _Program._
- The Darien Home page has been modified to add Darien-specific content (e.g. a Darien navi and a link to a Darien Talk board.)
- New Info/Content pages (e.g. "Ecology") are being added - these serve as informative teaching guides for Teachers and Students to refer to. (These pages should have near zero mechanical functionality.)
- On the subject of a Darien navi, a new way of navigating the Darien Program is currently being considered. WARNING: at the moment, this new way _does_ cause some visual UI clashing with the overall navigation for Zooniverse Classroom; we're still rethinking the UI design here.
This PR's updates will _only_ affect Darien components, and should not affect any Astro or general …

WildCam Lab Classrooms - 2018 Rebuild - part 5

---

package-lock.json
package.json
src/components/classrooms/ClassroomsManager.spec.jsx
src/containers/layout/AuthContainer.spec.jsx

This is a first pass at just general updates. I updated the allowed node and npm versions, so I could run npm 6 (node 10 will probably be LTS this fall). I ran `npm audit fix` to get non-breaking updates to the packages. I removed old tests that fail and don't apply anymore that weren't updated as we were rapidly developing last fall. 
The rest of the updates that can be done will have to be done manually since they are major version updates. Most of them are related to webpack and babel.

Run npm audit fix. Remove tests that don't apply anymore

---

src/components/Main.jsx
src/components/astro/AstroClassroomsTable.jsx
src/containers/layout/AuthContainer.jsx
src/index.jsx

Fixes #121. This is built on zooniverse/panoptes-javascript-client#97 (up to you if you want to install from github or use `npm link` to test).
I refactored the oauth initialization to include `customRedirects: true` because this app is managing the redirects on its own. I updated the redirect code in the `AuthContainer` to store the redirect in localStorage regardless of what page you're on. I also moved the initial login check to `Main` and added a general status loading page before we know if there's a user or not which just seems like good general practice.

Manage our own oauth redirects. Add a initialization loading page.

---

package-lock.json
package.json

This PR updates the PJC dependency to 2.11.0, which - in conjunction with PR #129 - allows the Edu API Front End to redirect users back to the page they were looking at, after a successful sign in process.
I'm going ahead and merging this, since #129 requires this latest PJC.

Update Panoptes JS Client to 2.11.0

---

src/modules/wildcam-classrooms/components/AssignmentForm.jsx
src/modules/wildcam-classrooms/components/AssignmentsListForStudents.jsx
src/modules/wildcam-classrooms/components/ClassroomForm.jsx
src/modules/wildcam-classrooms/components/ClassroomsList.jsx
src/modules/wildcam-classrooms/components/StudentsList.jsx
src/modules/wildcam-classrooms/containers/WildCamForEducators.jsx
src/modules/wildcam-classrooms/containers/WildCamForStudents.jsx
src/modules/wildcam-classrooms/containers/WildCamStudents.jsx
src/modules/wildcam-classrooms/ducks/index.js
src/programs/darien/DarienProgram.jsx
src/programs/darien/common/DarienNavi.jsx
src/programs/darien/pages/DarienEducators.jsx
src/programs/darien/pages/DarienStudents.jsx
src/programs/gorongosa/pages/GorongosaEducators.jsx

This PR updates WildCam Darien/the WildCam Lab components with the following:
- Students now have their own "For Students" page, which allows them see all Assignments they're a part of.
- Not yet implemented: the ability for Students to actually start the Assignments they're a part of. This will require some external setup (i.e. enabling group work for WildCam Darien) and a new config setup (i.e. the ability for a Program to specify the URL where students need to perform Assignments).
- Teachers can now add/remove students from Assignments, and can remove students from Classrooms.
- This was a feature I forgot to properly implement before.
- Improvement needed: list of students added to Assignment should be retained after the transition to/from the Subjects selection feature.
Merging.

WildCam Lab Classrooms - 2018 Rebuild - part 8

---

package.json

This PR updates `panoptes-client` to v2.11.2, which is necessary for compatibility with one of Panoptes's upcoming updates. See https://github.com/zooniverse/panoptes-javascript-client/pull/103 for further details. (The short of it: if we don't update PJC, users won't be able to login after Panoptes updates its `doorkeeper`.)
**This PR is mostly for documentation.** PJC 2.11.2 has already been _installed and deployed_ as part of PR #136 (ongoing WildCam updates for HHMI), and I'll sort out the resulting merge conflict in that PR.
Merging.

Update PJC to 2.11.2 for compatibility with new Panoptes updates

---

src/modules/wildcam-classrooms/components/AssignmentsListForStudents.jsx
src/modules/wildcam-classrooms/components/ClassificationsDownloadButton.jsx
src/modules/wildcam-classrooms/text.en.js
src/modules/wildcam-classrooms/text.es.js
src/programs/darien/wildcam-darien.classroom-config.js
webpack.config.js

This PR focuses on adding a basic "Download My Classifications" button to Student Assignments on WildCam Lab programs.
- The "Download My Classifications" button will download _(in chunks)_ all of a (logged-in) user's Classifications from a single Workflow (i.e. assignment)
- This CSV is still somewhat basic, and lacks any map information - a separate call to Carto's DB needs to be made and manually joined to the data from Classifications. Good luck with the load, eh!
- ❗️ EXTERNAL BUGFIX: See zooniverse/Panoptes-Front-End#5256 and zooniverse/Panoptes-Front-End#5259 for a massive bugfix that prevented non-admin/non-project owner users from working on an Assignment on PFE.
- This error was previous undetected on WildCam Darien Lab because I, Shaun, was always logged in with my account, …

WildCam Lab Classrooms - 2018(?!?) Rebuild - part 15

---

src/modules/wildcam-classrooms/components/AssignmentsListForStudents.jsx
src/modules/wildcam-classrooms/text.en.js
src/modules/wildcam-classrooms/text.es.js
src/styles/components/wildcam-classrooms.styl

In the Student's Assignments list, the first time a user clicks on any "Start Assignment" button, they are provided a reminder to to login at `zooniverse.org` before starting the assignment.
After that reminder is show, all "Start Assignment" buttons take the user to their assignments, as usual.
Merging

WildCam Lab 2019 pt 5 - Add Reminders to "Start Assignment"

---

src/components/astro/AstroClassroomsTable.jsx
src/components/astro/ExportModal.jsx
src/containers/astro/AstroClassroomsTableContainer.jsx
src/ducks/caesar-exports.js

Caesar's API for requesting data exports has changed which is the likely source of the issues in #148. This is a partial fix to the issue. I've updated the requests to use `subject_reductions` in the request payload as well as changed `workflow_id` to `exportable_id` in the store. 
I'm unsure if anymore client side changes need to be made, but there are some possible server side bugs now being exposed now that the request is properly being made. See https://github.com/zooniverse/caesar/issues/859

Fix exports

---

src/programs/gorongosa/wildcam-gorongosa.map-config.js

This PR updates the CSV download for WildCam Gorongosa Lab (the **Map** downloads, not the Assignments downloads). Without this PR, the downloaded CSVs are missing a few columns (behaviour, etc), have different column names ('location' instead of 'image_url'), and columns that are out of order.
The first two issues were caused by me having previously taken the initiative to streamline the Gorongosa CSV downloads to match Darien's CSV downloads. Whoops, that was a mistake of over-optimisation without checking user reqs. The third issue is caused by... a wizard did it. I have no idea why the SQL results from Carto have the columns in a semi-random order.
Merging and deploying.

WildCam Lab 2019 pt9 - WildCam Gorongosa Lab CSV

---

src/modules/wildcam-classrooms/components/AssignmentForm.jsx
src/modules/wildcam-classrooms/components/AssignmentsListForStudents.jsx
src/modules/wildcam-classrooms/components/ClassroomForm.jsx
src/modules/wildcam-classrooms/containers/WildCamForStudents.jsx
src/modules/wildcam-classrooms/ducks/index.js

This PR fixes an issue where WildCam Classrooms kept fetching ALL assignments from the `/assignments` endpoint. This patch makes sure that only Assignments from the current Program are fetched.
Ready to go

WildCam Lab 2019 pt11 - Fix "Pulling too many Assignments" Bug

---

src/programs/gorongosa/wildcam-gorongosa.map-config.js

There are a few errors with WildCam Gorongosa Lab:
1. SQL aggregation selects forgot to implement the `num_classifications >= 5` threshold. This threshold (from the original WildCam Gorongosa Lab) prevents poorly-vetted aggregation results from popping up on the Map Explorer, Downloads results,e tc.
2. `species_count` was being incorrectly mapped to `agg.num_classifications` instead of `agg.most_likely_number_of_animals`. `agg.num_classifications` actually refers to the number of classifications that contributed to the aggregated result, not the number of animals in the image.
This PR fixes these issues, and also expands the view on Gorongosa's SQL queries in the config so it's easier to understand what's going on.
Merging, but not deploying until Monday.

Fix WildCam Gorongosa Lab's SQL Queries

---

package-lock.json
package.json

This PR updates Panoptes JavaScript Client to 3.1.0, which allows single-sign on, on the *.zooniverse.org domains.
Also, I ran `npm audit fix` to update a few packages.
I'm merging and deploying this 👌

Update PJC to 3.1.0, enabling SSO

---

src/containers/astro/AstroClassroomsTableContainer.jsx

Updates the javascript code that transform the caesar reduction export into a friendly human readable CSV for analysis in the classroom activities. This adds the new computer classification column. @lcjohnso asking for review from you to confirm that the subject metadata will be updated to use `!Computer_Classification` and the related extract rules will use `Computer Classification: '$.subject.metadata['!Computer_Classification']'` like I've used on staging: https://caesar-staging.zooniverse.org/workflows/3037#extractors. The code I've written here depends on the rule setting that value to `Computer Classification`, line 111 looks for this as `'data.Computer Classification'`.

Add computer classification column

---

src/containers/astro/AstroClassroomsTableContainer.jsx

We had a report that the header labels in the CSV export for the relaunched Galaxy Zoo activity were reversed. This was confirmed by comparing the tasks from the original project to the new project, that elliptical is now the first choice in the question task list.
Caesar has no knowledge of the human labels for question task answers, so when you get a reducer export, the labels are in array order of the task answer list, like `data0`, `data1`, etc. I take those labels and give them human labels again, `spiral`, `elliptical`, etc. This relabeling is hardcoded and assumed the order of the answers in the task remained the same. This PR fixes the ordering for the new project.
Long term, we should consider a few of options:
1. Zooniverse classrooms requests the workflow from Panoptes to get …

Reverse spiral and elliptical for export

---

src/programs/gorongosa/wildcam-gorongosa.map-config.js

This fixes an issue with the CSV downloads on WildCam Gorongosa's Map Explorer, where `species_count` weren't always giving values in the way that users expect.
- In the CSV download, the `species_count` should always have a _single number value_ (instead of a numerical range) to allow for mathematical calculations, e.g. when processing the data on Excel.
- This means that when `species_count` says `"11-50"`, it should be translated to `"25"`, etc. See https://classroom.zooniverse.org/#/wildcam-gorongosa-lab/explorers/data-guide/ for users expect.
Mergin' today, deployin' Monday.

Fix species_count for Wildcam Gorongosa Lab Map Downloads

---

package-lock.json
package.json

Update Zooniverse-React-Components to v0.9.1, which includes security vulnerability patches, but no changes.
On other repos I've been using this as an excuse to also run an `npm audit fix`, let me know if would also like me to open that PR, or I'd be happy to review that PR, and get both in for a deploy.

Update ZRC, add dev dependency babel register, run npm audit fix

---

package-lock.json
src/components/GlobalNotification.jsx
src/components/Main.jsx

Context: there is currently an issue where users cannot login via Oauth on `*.zooniverse.org` websites (such as `classroom.zooniverse.org` - see https://github.com/zooniverse/operations/issues/459). The team is still working on a solution, but in the meantime we need to inform teachers and students about the workaround that allows logging in.
- This PR adds a GeneralNotification component that appears on every page.
- The GeneralNotification can be manually dismissed (this state is retained until the website is refreshed)
- The GeneralNotification will NOT appear if the user is already signed in, because they don't need the workaround information
- The General Notification has been updated with a message specific for the recent Sign In issues.
I'm going ahead and merging + deploying this.

Add warning for Sign In issues (Oct - Nov 2020?)

---

src/components/GlobalNotification.jsx
src/components/GlobalNotification.md
src/components/Main.jsx

This PR removes the global notification, which was most recently set up in Dec 2020 to inform users of a resolved problem.
- This PR also adds instructions on how to reactivate the Global Notifications should warnings/updates/etc be necessary in the future.

Remove Dec 2020 global notifications

---

Dockerfile
README.md
docs/wildcam/README.md
package.json

This repo was recently renamed from `edu-api-front-end` (Education API Front End) to `classroom` (to properly reflect its actual branding of Zooniverse Classrooms). This PR changes several name references to reflect that.
- Updated `package.json` and a few `README`s
- Update required node version to >= 14
One sec, gonna wipe then reinstall packages to test out Node 14.

Change name to Zooniverse Classroom + Node 14

---

README.md
src/modules/wildcam-map/ducks/index.js
src/programs/darien/wildcam-darien.map-config.js
src/programs/gorongosa/wildcam-gorongosa.map-config.js
webpack.config.js

Requires: https://github.com/zooniverse/labs-datasette-api/ (new API)
Context: the Carto map database requirement (for WildCam Labs) is being retired. The map database will be replaced by a Zooniverse-hosted Datasette solution.
This PR updates WildCam Gorongosa Lab and WildCam Darien Lab to integrate with the new Labs Datasette API.
Goals:
- Corollary: A teacher should be able to create Assignments. i.e. make sure to test submitting the Create Assignment action to the API!
WIP

WildCam: discard Carto, use Datasette

---

src/components/common/Home.jsx

Wildwatch Kenya Lab (see https://github.com/zooniverse/classroom/pull/224) is currently in the process of development. The Program has been added to the Education API (production) since Tuesday for dev/preview purposes, but this unfortunately means that the Program is now listed on the live (!!!) Zooniverse Classrooms home page.
This PR is a quick temporary fix that prevents WWKenya from being listed on the home page.
Gonna get this merged & deployed as soon as possible.

Hack/hotfix: temporarily hide Wildwatch Kenya from home page

---

package-lock.json

This PR is a preemptive strike on outdated dependencies, before dependabot bombards us with more emails.
- Mostly it's just a matter of reinstalling packages, and running `npm audit fix`.
- ⚠️ Unfortunately, running `npm audit` shows there are STILL a number of "high severity" dep issues that can't be fixed without overhauling the (sigh) Webpack setup from v4 to **Webpack 5**
- But I think they DON'T need to be fixed, since they're mostly build-related, not UI-related (i.e. not user-facing)?
Some notes on... the problematic dependencies => what's using it => what's the probem => do we need to worry about it now?:
- dns-packet  <5.2.2 => used by webpack-dev-server => Memory exposure when calling specific URLs => build side, not a problem
-  serialize-javascript  <3.1.0 => used by …

May 2021 maintenance update

---

package-lock.json
package.json
src/modules/wildcam-map/containers/MapVisuals.jsx
src/programs/darien/wildcam-darien.map-config.js
src/programs/gorongosa/wildcam-gorongosa.map-config.js

Affects: WildCam Lab's Map Explorer (i.e. Gorongosa, Darien, and Kenya)
Context: ever since Wildwatch Kenya Lab, we realised that the "extra data layers" on the map (the ones that represent biomes/habitats, park boundaries, etc) actually have a lot of important information that can be surfaced.
This PR adds an optional Tooltip feature. By mousing over certain Features on those Extra Data Layers, a Tooltip will appear displaying all the information we have on that map feature.
- A basic "bindTooltip" call has been added. This creates a default tooltip.
- NOTE: for an extra data layer to have a tooltip, it needs to have its **layer.style.interactive** value set to **true.**
- Required secondary functionality: now every time a layer is added/removed (via the built-in layer controls), the …

Jun 2021 hackday: add optional Tooltips for layers

---

.github/workflows/deploy_staging.yml
package.json
src/containers/layout/AuthContainer.jsx

This PR adds the `build-staging` script, so our [staging website](https://classroom.preview.zooniverse.org/) uses Staging instead of Production data.
- Currently, https://classroom.preview.zooniverse.org/ connects to Production because there's only one `build` script, and that's for prod.
- Note that the staging website is auto-deployed via Github Actions
Code ready to review, but mind you, I can't seem to get `npm run build-staging` (nor `npm run build`) on my machine for self testing, due to a bunch of configuration shenanigans. Sigh, don't ask, I keep getting Python errors even though this shouldn't be using any Python. (`npm run start` works fine though, so I know the website code is working OK, it's my local machine config that's borked.)
@camallen Can you please take a look at this? …

Add `build-staging`

---

package.json

PR #249 failed in its intent - `npm run build-staging` was failing. PR #248 should have been merged first, since there were essential Webpack 5 upgrades. This PR attempts to fix 249.

Fix build-staging for Webpack 5

---

.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml

Per azure-cli/issues/20154, `azcliversion` should be omitted so defaults to latest, or set to latest. For consistency with other Zooniverse repos this PR removes `azcliversion: 2.29.2`.

Remove azcliversion from github actions

---

src/lib/zooniversal-translator.js
src/programs/darien/DarienProgram.jsx
src/programs/gorongosa/GorongosaProgram.jsx
src/programs/kenya/KenyaProgram.jsx

Fixes #255
This PR fixes an issue where a use can choose a language in WildCam Lab Program X, then that language choice would persist in WildCam Lab Program Y EVEN IF Program Y doesn't support that language
- With this PR, each WCL Program has a list of _acceptable languages_ (Kenya/Gorongosa: English/default only. Daríen: English/default or Spanish)
- When a user loads a WCL Program page but has an _unacceptable_ language stored in their settings, the settings will be reset and the page will _reload_
This approach is crude, but the better alternative (replacing the Zooniversal Translator hack with the proper `counterpart` library) would take a bit more time investment.
Merging, go

Enforce acceptable languages for WildCam Lab Programs

---

src/modules/wildcam-classrooms/components/AssignmentForm.jsx

Closes #256 
Currently, non-custom WCLab Programs can't set the Classification Target ("number of photos each Student needs to classify") for Assignments. This was a side effect of: 1. the rule that Classification Target cannot exceed number of selected Subjects and 2. the fact that non-custom WCLab Programs can't select Subjects.
With this PR, we have new behaviour:
- For custom WCLab Programs (i.e. the ones where you can select specific Subjects for Assignments):
- (new) the Classifications Target field is _always visible_
- (same) the Classifications Target field has a minimum value of 0, and a maximum of (number of selected subjects)
- For non-custom WCLab Programs (i.e. the ones where you use the main project's workflow)
- (new) the Classifications Target field is _always visible_
- …

Allow non-Custom Programs to set Classifications Target

---

.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml
Dockerfile
package.json

#259 bumped the npm version to 7. This upgrades Node to match.
Builds are broken at the moment because Node 14 bundles with npm 6. This should fix that by building with Node 16/npm 8.

Build with node 16.

---

package-lock.json
package.json
webpack.config.js
webpack.production.config.js

Upgrade `webpack-dev-server` to the latest version, which should fix a bunch of annoying dependabot security alerts for outdated dependencies.
To test out the dev server, run `npm start` and browse the app on https://local.zooniverse.org:3998
Closes #267.

[Security] Upgrade webpack-dev-server to v4

---

.github/workflows/build_branch.yml
.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml
package.json

All CI and deploy builds should use `NODE_ENV=production` (see abab70e093e1abd53b09c489e37678293d8c11c3.)
Fixes this warning.
```log
WARNING in DefinePlugin
Conflicting values for 'process.env.NODE_ENV'
```

Use production builds for CI

---

package-lock.json
package.json
src/containers/common/JoinPageContainer.jsx

- Remove `query-string`.
- Use the `URLSearchParams` API to get join tokens for classrooms.
Towards #327.

Remove `query-string`

---

src/components/classrooms/ClassroomEditor.jsx
src/components/classrooms/ClassroomsManager.jsx
src/containers/assignments/AssignmentFormContainer.jsx
src/containers/assignments/AssignmentFormDialog.jsx
src/containers/classrooms/ClassroomFormContainer.jsx

Wrap the connected assignment form and classroom form in `Layer`. This makes sure that the Redux store context is passed down correctly to the layer contents.
Closes #325.

Fix Redux store context for Layer

---

src/containers/common/JoinPageContainer.jsx

The URL parameter for joining a classroom is `token`, not `joinToken`, but the API parameter is `joinToken`.
At the moment, joining a classroom will error with `joinToken is null`.

Fix joining a classroom

---

package.json

Per https://github.com/zooniverse/classroom/blob/master/src/lib/config.js environment is defaulting to `staging` for `build` script.
This PR defines the node environment to `production` for the `build` script. 
This will change the staging classroom site to point to the production Panoptes database. Is that what we want or shuold we revisit #330 and #323?

Define NODE_ENV for build script

---

src/modules/wildcam-classrooms/components/ClassificationsDownloadButton.jsx
src/programs/kenya/wildwatch-kenya.classroom-config.js
src/programs/kenya/wildwatch-kenya.map-config.js

This fixes some issues with the Student assignment CSV downloads ("My Data") on Wildwatch Kenya.
- **Issue 1:** previously, downloaded Student assignment CSVs would be missing several fields/columns. This was due to incorrect SQL columns being specified, resulting in a silent error where no Subject data was available.
- **External fix required:** [Kenya database](https://classroom-maps-api.zooniverse.org/kenya) needs to have list of Subjects updated to match current production data
- **Issue 2:** previously, attempting to download data for an Assignment with 0 Classification would lead to a silent error. Now, a CSV file is downloaded with the text "no data"
- **Tweak 1:** when asking the SQL server for Subject data, Wildwatch Kenya now specifically asks for specific Subject IDs instead of …

Wildwatch Kenya: fix Student Assignments's data downloads

---

src/programs/kenya/wildwatch-kenya.classroom-config.js
src/programs/kenya/wildwatch-kenya.map-config.js

Follows #351
In that PR, I mistakenly removed `sbj.month` and `sbj.year` from the `selectAllSubjects` SQL query, because I thought those columns didn't exist in the database. Well, they do! Sorry about that, columns.

Wildwatch Kenya: fix 'year' and 'month' mistakenly removed from selectAllSubjects

---

src/components/common/Home.jsx
src/programs/darien/pages/info/DarienEducatorsIntro.jsx
src/programs/darien/pages/info/DarienStudentsIntro.jsx
src/programs/gorongosa/pages/info/GorongosaEducatorsIntro.jsx
src/programs/gorongosa/pages/info/GorongosaStudentsIntro.jsx
src/programs/kenya/pages/info/KenyaEducatorsIntro.jsx
src/programs/kenya/pages/info/KenyaStudentsIntro.jsx
src/styles/components/wildcam-intro-page.styl

Affects: Wildwatch Kenya Program
This PR enables Wildwatch Kenya Lab for the public, as per San Diego Zoo's request. (See email: "Re: Wildwatch Kenya Education Portal", 18 Jun 2022)
- WWKenya now appears as a Program on the home page
- A new bit of support text added to the Educator's intro page
- UI tweak: `<a>` links on WildCamLab intro pages are now visually distinguishable with an underline. (Credit to Jim with showing me that article about accessible hyperlinks/hyperlinks with the same colour as the text.) 
- Oh, also, WildCamLab intro pages are now properly tagged.
As soon as this is merged, I'm deploying Classrooms and WWK Lab goes live!

Wildwatch Kenya Lab: Jun 2022 Launch!

---

src/components/astro/AstroHome.jsx

Update Drive link for Instructors Guide to new, post-GSuiteMigration URL (https://drive.google.com/drive/folders/1HS-yV9EUyMTjvoxiDasKpQINAIBJX_d6?usp=sharing).

Update Instructors Guide Link

---

src/components/classrooms/ClassroomEditor.jsx
src/containers/classrooms/ClassroomEditorContainer.jsx

Programs: Zooniverse In Schools, Astro 101
This PR updates Astro 101's Classroom Editor [(example)](https://local.zooniverse.org:3998/#/astro-101-with-galaxy-zoo/educators/classrooms/467) so that it's "student progress table" shows _all available assignments,_ not just GZ and Hubble.
- Previously, Astro 101's Classroom Editor was hardcoded to only display 2 assignments: Galaxy Zoo and Hubble. ZIS adds a third assignment - also title _Zooniverse In Schools_ - which needs to be displayed.
- UI change: exactly what I just said
- Behaviour change:
- previously, each assignment's progress count could _individually_ switch its student progress display between percentage complete (e.g. 33%) or whole numbers (e.g. 6 / 9 ) by clicking on the assignment name in the table header. Now, clicking on …

Zooniverse In Schools/Astro 101 - Classroom Editor shows all Assignments

---

package-lock.json
package.json

Webpack 5 uses asset modules, so `file-loader` isn't needed any more.

Remove file-loader

---

package-lock.json
webpack.config.js

- `npm update webpack-dev-middleware` to fix a crashing bug in `memfs` 3.4.1.
- allow hostnames other than `localhost`.
- open the dev site automatically in your default browser.

Upgrade webpack-dev-server

---

webpack.production.config.js

Remove the image minimiser from the production build config, so that CI builds will run again.

Remove ImageMinimizerWebpackPlugin

---

src/modules/wildcam-map/containers/MapControls.jsx
src/styles/components/wildcam-map.styl

Related: #838 
Affects: Map Explorer (for WildCam Gorongosa Lab, Darien, and Kenya)
This PR adds a new notice to the Map Explorer, so teachers & students are aware that there's an ongoing issue with the Maps API server that's being investigated.
Merging and deploying ASAP, as issue 838 is still ongoing. 
The updates in this PR are intended to be temporary and should be reverted as soon as 838 is closed.

MapExplorer: add notice for issue #838

---

package-lock.json
package.json

This PR removes `express`, which appears unused and replaced with webpack-dev-server

Uninstall express (unused)
